export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const CLEAR_STORE = "CLEAR_STORE";
export const RETRIEVE_TRANSACTION = "RETRIEVE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const MODIFY_TRANSACTION = "MODIFY_TRANSACTION";
export const CLEAR_MODIFICATION = "CLEAR_MODIFICATION";
